# -*- coding: utf-8 -*-
"""tablas y graficas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11KJRuAMXZYCva7YG5-Td-RDTBqQmfqJ6
"""

import numpy as np
import pandas as pd

df = pd.DataFrame({
    "dato": pd.date_range(start="2020-05-01", periods=100, freq="D"),
    "temperatura": np.random.randint(18, 30, size=100)+
                   np.random.random(100). round(1)
})
df.head()   #imprimir encabezado

"""#hemos creado un marco de datos que contiene mediciones de temperatura durante un periodo de 100 días. la funcion date_range de pandas
#puede utilizarse para generat un rango de fechas con una frecuencia personalizada. los valoresde temperatura se generan de forma aleatoria utilizando las funciones numpy

-ahora podemos empezar con las funciones

1. shift
es una op. habitual para desplazar los datos de las series temporales.
"""

df["temperatura_larg_1"]= df["temperatura"].shift(1)
df.head()

df["temperatura_larg_1"]= df["temperatura"]\
.shift(1,fill_value=df.temperatura.mean())
df.head()

df.semanalmente = df.resample("w", on="dato").mean()
df.semanalmente.head ()

df.set_index("dato").asfreq("w").head()

df.set_index("dato").rolling(3).mean().head()

df.set_index("dato").rolling(3, center=True).mean().head()